### ISSUE TITLE
SG-1000 SN76489 PSG chip noise generation

### ISSUE THREAD

**Issue by siriokds** [drhelius/Gearsystem#100]
Hi,
SMS (1 and 2), Genesis and Game Gear have and integrated PSG and, in the noise channel implementation, the tapped bits are bits 0 and 3 ($0009), fed back into bit 15. 

For the SG-1000, Othello Multivision, SC-3000(H) and Colecovision, the tapped bits are bits 0 and 1 ($0003), fed back into bit 14.

**Comment by drhelius** [comment]
This is an easy fix.
Thanks for reporting!
