### ISSUE TITLE
SN76489 HALT to Z80

### ISSUE THREAD

**Issue by siriokds** [drhelius/Gearsystem#101]
Hi again,
the SN76489 audio chip present on: 
SG-1000 Mark I
SG-1000 Mark II rev1 and rev 2
Othello Multivision
Colecovision

When it's accessed (e.g. out ($7F),a) it HALTs the CPU for 32 cycles (avg value). It's also described in the SN76489 datasheet...

You can hear the difference in the "Star Jacker" title screen for SG-1000/SC-3000.

**Comment by drhelius** [comment]
Yes, I know. I already added this difference in 3390eb0.

I already implemented this sometime ago for Gearcoleco but forgot to include it in Gearsystem for SG-1000.

Thanks anyway.

**Comment by siriokds** [comment]
Thank you!
