### ISSUE TITLE
Automatic detection of SG-1000 games

### ISSUE THREAD

**Issue by nanitaro** [drhelius/Gearsystem#103]
This may be a problem with the Libretro core only.
Reproduction Procedure.
Set all system, region, and mapper options to automatic.
Load the SG-1000 ROM in that state.
The colors will be in accordance with the master system (dark color palette).

If an SG-1000 ROM is loaded, I would like it to emulate the SG-1000 system in auto mode.

**Comment by drhelius** [comment]
Yes, you are right. I totally missed it on libretro.
