### ISSUE TITLE
Get rid of left side overscan.

### ISSUE THREAD

**Issue by roioros** [drhelius/Gearsystem#108]
Hello!

First of all, thank you very much for this fantastic emulator.

I would like to know if there is a possibility to disable the overscan on the left side of the screen, as it is very annoying.

Here is an example:

![Sonic The Hedgehog (UEB)  ! zip - 2024-12-15 143158](https://github.com/user-attachments/assets/5cec8d4a-2ce8-4ad9-8534-ab1dcb998538)

Thank you so much!

**Comment by drhelius** [comment]
Thanks for your words.

This is not overscan, some games blank 8 pixels of the actual screen so sprites clip out nicely on the left (https://www.smspower.org/forums/9222-BarOnTheLeftSideOfTheScreen). 

I can add an option to crop it but you will crop valid display in some other games than don't use this feature (ie some vertical scrollers).

**Comment by roioros** [comment]
Hi!

Ah, I understand, if it is not too much to ask, could you add an option to eliminate those 8 pixels on the left, for the games that need it I would activate that option again.

Thank you so much again!

**Comment by drhelius** [comment]
Added an option to auto detect the left bar and hide it. You can also force it to always hide it.
It only works for SMS.

**Comment by roioros** [comment]
Great!

Thank you so much, I am super grateful.

Congratulations again for all your emulators, they are fantastic.
