### ISSUE TITLE
Corrupted FM audio in Shinobi after some combination of load state+reset

### ISSUE THREAD

**Issue by alice-mkh** [drhelius/Gearsystem#109]
An example of an affected savestate: [Shinobi (USA, Europe).zip](https://github.com/user-attachments/files/18241433/Shinobi.USA.Europe.zip)

Often after a reset+load the sound is garbled in different ways. It's not consistent, and I haven't seen it happening in other games.

Version: both 3.5.0 and current master

**Comment by alice-mkh** [comment]
Sorry, sent too early

**Comment by drhelius** [comment]
thanks, I was able to reproduce it

**Comment by alice-mkh** [comment]
Oh thanks, I was almost done making a video recording ^^

**Comment by drhelius** [comment]
I think I got it, I cannot longer reproduce it.
Your bad savestate should work now.

**Comment by alice-mkh** [comment]
Yep, can confirm it works. Thanks!
