### ISSUE TITLE
Crash when loading older savestates

### ISSUE THREAD

**Issue by alice-mkh** [drhelius/Gearsystem#113]
E.g. the one from #109 is affected. New states work fine.

```
#0  0x0000000000550e90 in SegaMemoryRule::PerformRead (this=0xae7d10, address=21318) at ../../src/SegaMemoryRule.cpp:53
#1  0x000000000053f098 in Memory::Read (this=0xb3dcc0, address=21318) at ../../src/Memory_inline.h:30
#2  0x000000000054936f in Processor::Disassemble (this=0xce9b20, address=21318) at ../../src/Processor.cpp:424
#3  0x0000000000548ebf in Processor::DisassembleNextOpcode (this=0xce9b20) at ../../src/Processor.cpp:332
#4  0x0000000000548724 in Processor::RunFor (this=0xce9b20, tstates=1) at ../../src/Processor.cpp:170
#5  0x0000000000531071 in GearsystemCore::RunToVBlank
    (this=0x756340, pFrameBuffer=0x7fffd6efd010 "", pSampleBuffer=0xc10d30, pSampleCount=0x7fffffffe6f8, step=false, stopOnBreakpoints=true) at ../../src/GearsystemCore.cpp:153
#6  0x00000000004291c5 in emu_update () at ../desktop-shared/emu.cpp:113
#7  0x0000000000443466 in run_emulator () at ../desktop-shared/application.cpp:536
#8  0x0000000000442327 in application_mainloop () at ../desktop-shared/application.cpp:111
#9  0x000000000042388b in main (argc=1, argv=0x7fffffffe888) at ../desktop-shared/main.cpp:78
```

Regressed somewhere between 8cbe460079c8d77250e4930f54fc27c734aeaa07 and c373f96999a2db5c26bbb7f929c82f052cdaf28f, but I don't know the exact commit

Version: master

**Comment by drhelius** [comment]
Yes, sorry, I had to change save states for light phaser support. I will probably have to change them again for new features. 

The commit that probably broke them is c373f96999a2db5c26bbb7f929c82f052cdaf28f

I'll document this in the next release that will be in just a few days.

**Comment by alice-mkh** [comment]
I mean changing them is fine, but surely it shouldn't crash, just reject them?

**Comment by drhelius** [comment]
You are right I will probably improve save states in the future, including some metadata, a screenshot, etc.

**Comment by alice-mkh** [comment]
Would you accept a PR for checking savestate size and rejecting if they are too small?

**Comment by drhelius** [comment]
Not for now, I think. 

I rather prefer adding metadata to the savestate in the form of a header with a version and other things like timestamp, title of rom, rom CRC, screenshit, etc.

Same size does not mean correct savestate.

And you will need to store the expected size in code, or calculate that dynamically which is worse because it will need two passes over the de-serialization.

I Wil create an issue to improve the save states with a header.

**Comment by alice-mkh** [comment]
Mm, ok. I need to add savestate versioning downstream either way, so I'll do that for now.
