### ISSUE TITLE
Mark III game Final Bubble Bobble (Japan) (No-Intro) runs as a glitchy Game Gear game

### ISSUE THREAD

**Issue by ensra** [drhelius/Gearsystem#15]
It looks very strange.

![2018-05-02-162301_1502x923_scrot](https://user-images.githubusercontent.com/29542929/39532637-1c7d6512-4e25-11e8-8cc3-c7a8bc040879.png)
![2018-05-02-162215_1577x958_scrot](https://user-images.githubusercontent.com/29542929/39532641-1feba6b4-4e25-11e8-9252-227a99e199ac.png)
![2018-05-02-162243_1554x923_scrot](https://user-images.githubusercontent.com/29542929/39532648-2274fce6-4e25-11e8-8daa-00249f2a1817.png)

How it looks in Genesis Plus GX:

![2018-05-02-162609_1367x954_scrot](https://user-images.githubusercontent.com/29542929/39532856-8e6f16f2-4e25-11e8-94bb-0e8a8ce8d143.png)
![2018-05-02-162540_1426x958_scrot](https://user-images.githubusercontent.com/29542929/39532861-9186440a-4e25-11e8-9d2f-39a7af494c19.png)

**Comment by drhelius** [comment]
Fixed!
