### ISSUE TITLE
Permission to add Gearsystem to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [drhelius/Gearsystem#22]
Hi there,

we would like to seek your permission to include Gearsystem as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by drhelius** [comment]
Thanks for your interest. No problem here, it's perfectly fine to include Gearsystem as a free DLC for RetroArch on Steam.

**Comment by twinaphex** [comment]
Thank you!

**Comment by LibretroAdmin** [comment]
Hey @drhelius ,

it took a while but both Gearsystem and Gearboy are up now on Steam as of today!

https://store.steampowered.com/app/1227485/RetroArch__Gearboy/

https://store.steampowered.com/app/1227484/RetroArch__Gearsystem/

**Comment by drhelius** [comment]
That's great news, thanks for all the work an support!

**Comment by LibretroAdmin** [comment]
Is Gearcoleco available as a libretro core too? If it is, would we have your approval to add that to our buildbot and as a Steam core DLC too?

**Comment by drhelius** [comment]
Yes, Gearcoleco can be added as a free DLC for RetroArch on Steam too.
