### ISSUE TITLE
Gamepad: configuring D-Pad as default

### ISSUE THREAD

**Issue by Pat86** [drhelius/Gearsystem#24]
Just tried the latest windows version and it seems like its only possible to configure the action buttons for gamepads, but not the controls. Analogsticks are forced, but i want to use d-pad instead.

**Comment by drhelius** [comment]
Thanks for your feedback.

The gamepads I use to test automatically map the analog stick to the dpad so I assumed it's working nice.

I'll have a look.

**Comment by Pat86** [comment]
I'm using the Xbox One Wireless Controller fyi

**Comment by drhelius** [comment]
Fixed!
Now you can choose D-pad or analog stick.
It will be available in next release.
