### ISSUE TITLE
Gearsystem crash

### ISSUE THREAD

**Issue by dinglyburrow** [drhelius/Gearsystem#25]
Latest version quits out as soon as I try to open a rom from the menu. Using [open recent] works fine. Also in latest version I can't reconfigure the gamepad configurations. Same happens in Gearboy.

**Comment by drhelius** [comment]
Wow that was terrible.

I found the bug crashing the app when opening a rom but I don't know why it hasn't showed before as it was there for some time.

**Comment by drhelius** [comment]
I can't reproduce the problem with the gamepad reconfiguration. Is the same problem as in https://github.com/drhelius/Gearboy/issues/109 ??

**Comment by drhelius** [comment]
Could you test this?

https://github.com/drhelius/Gearboy/releases/download/gearboy-3.0.3/Gearboy-3.0.3-patch1-Windows.zip

**Comment by dinglyburrow** [comment]
Gearboy-3.0.3-patch1-Windows.zip fixes the rom opening bug, but doesn't let me reconfigure the gamepad controls.

**Comment by dinglyburrow** [comment]
Gearboy-3.0.3-patch1-Windows.zip fixes the rom opening bug, but doesn't let me reconfigure the gamepad controls.

**Comment by drhelius** [comment]
Thanks for your help. 
Do the gamepad buttons work at all?
Can you switch between analog stick and dpad?

**Comment by dinglyburrow** [comment]
I'm using the 8bitdo model fc30 gamepad (not the model with the analog sticks). Gamepad buttons don't reconfigure and the dpad doesn't function either with latest version.

**Comment by drhelius** [comment]
Deleting the file C:\Users\YOUR_USER\AppData\Roaming\Geardome\Gearboy\config.ini will erase the configuration.

Does it make any difference?

**Comment by dinglyburrow** [comment]
I deleted the config file - no change.

**Comment by drhelius** [comment]
I think it's a mapping problem. If we can confirm that I can include additional mappings in the app for specific controllers.

With [this tool](http://www.generalarcade.com/gamepadtool/) you can force a specific mapping. simply choose your controller or redefine the mappings and force it using "Set mapping as environment variable", then run the emulator.

**Comment by dinglyburrow** [comment]
Yep. That fixed it! :)

**Comment by drhelius** [comment]
Good news!
I'll add the mapping database in the next release.
