### ISSUE TITLE
Feature request: manual region setting for libretro

### ISSUE THREAD

**Issue by autofire372** [drhelius/Gearsystem#26]
When playing the GG version of Sonic Blast, I discovered that Gearsystem boots it as its Japanese counterpart, G Sonic, while Genesis Plus GX boots the international version from the same rom. I then noticed that Gearsystem's core options do not include a way to force the use of a particular region. Could manual region changing be exposed through libretro?

**Comment by drhelius** [comment]
Yes, no problem.
Thanks for reporting.

**Comment by autofire372** [comment]
Tried the fix; the resulting core no longer runs in RetroArch. It just acts like the core isn't there...

**Comment by drhelius** [comment]
Region forcing is working. 

Using SMS Export does the trick. But I found a bug in Game Gear IO preventing it to detect region other than Japan. 

It should be fixed now, setting it to "auto" will load the international version.

**Comment by vaguerant** [comment]
Continuing on from drhelius/Gearboy#141, concerning an issue that occurs on the libretro build for Wii U (possibly endianness-related):
> When launching the Master System game Choplifter (No-Intro: Choplifter (USA, Europe).sms) with Region set to "Auto", you get the Japanese "Sega Mark III" splash screen. Changing the Region to "Master System Export", you still get the Sega Mark III screen. However, if you change the Region to "Master System Japan", the game boots straight to the title screen, as it should on an Export machine.

I was able to identify another game exhibiting this issue. Under normal circumstances (e.g. real hardware) Zillion (No-Intro: `Zillion (Japan, Europe) (En,Ja).sms`) is a game which displays the Sega Mark III screen when booted on a Japanese machine, then continues to a title screen in Japanese. Pressing 1/Start will launch into an introductory story sequence also in Japanese. On export machines (both PAL and NTSC seem fine even though this specific ROM is denoted as Japan/Europe by No-Intro), there is no Sega Mark III screen and the title screen and intro are all in English. In Gearsystem on Wii U via RetroArch, this behavior is reversed: Region set to Auto or "Master System Export" results in the Japanese version starting up, while Region set to "Master System Japan" boots the game in English.

I will continue testing; I'm particularly curious whether Game Gear games are similarly affected.

**Comment by drhelius** [comment]
Just merged the fix into master

**Comment by vaguerant** [comment]
Nice, confirmed fixed on my end as well.
