### ISSUE TITLE
Nemesis (KR) not loading

### ISSUE THREAD

**Issue by dinglyburrow** [drhelius/Gearsystem#27]
Nemesis, the Korean rom file does not seem to work; system/region/mapper all set to auto.

https://www.smspower.org/Games/Nemesis-SMS

**Comment by drhelius** [comment]
I'll have a look.

Thanks for reporting.

**Comment by drhelius** [comment]
It looks like this cartridge uses a MSX mapper I haven't implemented yet but I will add it into a future release.

**Comment by drhelius** [comment]
Implemented MSX mapper. It will be included in next release.

This will enable the following games:

- Penguin Adventure (KR)
- Street Master (KR)
- Won-Si-In (KR)
- F-1 Spirit - The way to Formula-1 (KR)
- Cyborg Z (KR)
- Knightmare II - The Maze of Galious (KR)
- Super Boy 3 (KR)
- Nemesis (KR)
- Nemesis 2 (KR)
