### ISSUE TITLE
Libretro core does not load on Windows

### ISSUE THREAD

**Issue by autofire372** [drhelius/Gearsystem#28]
The Gearsystem libretro core does not run on Windows when built from source. Copying the resulting dll into the $RETROARCH\cores directory just results in RetroArch acting like it is trying to load a nonexistent core.

Cores from the libretro buildbot work fine, so maybe I'm doing something wrong. Using msys2, I `cd` into $GEARSYSTEM_SOURCE/platforms/libretro and run:
`make platform=win`

**Comment by drhelius** [comment]
Sorry, I don't have a clue, never tried building the libretro core on Windows. This is something I delegate to buildbot.

Buildbot is using this same repo for building all Gearsystem cores so it could be something bad in your toolchain.
