### ISSUE TITLE
Games scaled down or "letter-boxed"

### ISSUE THREAD

**Issue by mithical** [drhelius/Gearsystem#3]
### iPad Mini (7.0.2), iPhone 5s (8.0.2), iPhone 6 (8.0.2)

It seems there's some scaling issues on certain games. At first I thought that normal `.gg` ROM must be somehow smaller than the `.sms` ones but it seems that the letter boxing issue is occurring in both kinds on multiple devices, mostly those of bigger aspect ratios. 

I'm presuming there hasn't been any updates for the larger, recently released iPhone 6 and 6 Plus?  

Here's an example:
![original](https://cloud.githubusercontent.com/assets/3520542/4484560/253383be-49bd-11e4-8809-98b71c6fe411.jpg)

**Comment by drhelius** [comment]
This has been enhanced, GG games aren't letter boxed any more.
