### ISSUE TITLE
Libretro build failures (WiiU/Switch)

### ISSUE THREAD

**Issue by twinaphex** [drhelius/Gearsystem#31]
Hi there,

because of a recent change to this repo, several Libretro/RetroArch builds now broke down.

Both WiiU and Switch are affected -

http://paste.libretro.com/209726

http://paste.libretro.com/209729

Seems to be related to the MSX commit you pushed.

**Comment by drhelius** [comment]
I just pushed a commit that should fix this issue.
I was a missing source file that I added recently, I can't understand why other platforms are not failing or even my Travis CI test.

**Comment by twinaphex** [comment]
Thank you for the prompt response.

It's likely that it hadn't reached the other platforms yet so these were the first platforms where I could notice things weren't building.

**Comment by drhelius** [comment]
I just checked in Discord and they were indeed failing for all platforms.
I see the builds going back to normal now.
Thanks for reporting.
