### ISSUE TITLE
"SEEE-GAAA" chant missing from all GG games

### ISSUE THREAD

**Issue by autofire372** [drhelius/Gearsystem#32]
Many Game Gear games feature the "SEEE-GAAA" chant from Sega commercials of the era playing over the Sega logo on boot. This audio does not play in Gearsystem, but it does in Genesis Plus GX. Tested with Sonic Blast, Tails Adventure, and Coca Cola Kid.

**Comment by drhelius** [comment]
Thanks for reporting, I'll have a look at it.

**Comment by drhelius** [comment]
Fixed!
