### ISSUE TITLE
The timing of rendering scanline will off by 1 line

### ISSUE THREAD

**Issue by suzukiplan** [drhelius/Gearsystem#33]
The relationship between the timing at which the scan line I recognize is drawn and the value of the V counter:
|V counter|render scanline|
|---|---|
|$17|$18|
|$18|$19|
|$19|$1A|
|:|:|

Your implementation may be following:
|V counter|render scanline|
|---|---|
|$18|$18|
|$19|$19|
|$1A|$1A|
|:|:|

As a result, the execution timing of the H interrupt will shifted by 1 line, I confirmed:
![image](https://user-images.githubusercontent.com/7346381/88474468-a1b51d00-cf61-11ea-90df-e38aefa0f95c.png)

**Comment by drhelius** [comment]
Thanks for reporting.
Could you share the method you used to confirm this? Is the last corrupted line in the girl's image what you're talking about?

**Comment by suzukiplan** [comment]
I'm also making GameGear emulator (*for test [my Z80 emulator](https://github.com/suzukiplan/z80)), and faced the same problem.
![image](https://user-images.githubusercontent.com/7346381/88478032-f9628100-cf7f-11ea-9107-bba07f22e459.png)

**Comment by suzukiplan** [comment]
This problem can see in the opening of Madou Monogatari 1 (JP):
- launch game
- push start button
- choose "はじめ" (means starting)
- wait for about 1~2 minute

**Comment by drhelius** [comment]
I can see this issue in Genesis Plus GX too, it also shows a glitch but is different.

**Comment by drhelius** [comment]
I have tested it on a real GG and you are completely right, my version of Genesis Plus looks like it's doing it badly too.
Are you using this https://www.smspower.org/Homebrew/SMSVDPTest-SMS in your emulator?

**Comment by suzukiplan** [comment]
My GG emulator not has SMS compatible mode, so cannot use SMSVDPTest-SMS yet now...

Just to be sure, I have checked the code for Genesis Plus GX and it seems that the similar issue will occurs, because the v counter and draw scanline values are the same:
https://github.com/ekeeke/Genesis-Plus-GX/blob/15722b16ab5a539b14dba024bb008b5c6f22c202/core/vdp_ctrl.c#L2887-L2891

**Comment by suzukiplan** [comment]
FYI: I ported my GG emulator for SMS and tested with SMSVDPTest-SMS

|data test|misc test|sprite test|XScroll timing|
|---|---|---|---|
|![image](https://user-images.githubusercontent.com/7346381/89726670-025f5200-da58-11ea-851f-451ab96aba5a.png)|![image](https://user-images.githubusercontent.com/7346381/89726676-1905a900-da58-11ea-84af-2c7719bf5086.png)|![image](https://user-images.githubusercontent.com/7346381/89726690-39356800-da58-11ea-8d3d-0603e4c960f7.png)|![image](https://user-images.githubusercontent.com/7346381/89726695-4d796500-da58-11ea-862e-37b8e9388ffa.png)|

_My HCounter emulation is not perfect, but others may be okay._

**Comment by drhelius** [comment]
Thanks for all the feedback, I'm going to decouple the sprite rendering code from sprite processing in my emulator, in order to achieve this off by one issue and other colision and flag issues with sprites.

**Comment by drhelius** [comment]
Also note that these sms tests fail in a real gg because hcount timing is quite different between sms and gg, so if you are emulating both machines you have to take into account these differences.
