### ISSUE TITLE
Impossible jp instruction

### ISSUE THREAD

**Issue by WaferMouse** [drhelius/Gearsystem#34]
We found this when trying to reverse and fix the new GG Aleste game, hopefully the image speaks for itself. It looks as though somehow data got duplicated. This isn't just the debugger, either, the emulator actually jumps there. We found this bug because we were hacking Gearsystem with some primitive logging functions to figure out where/why the PC was jumping to RAM, and I've confirmed the same behavior in the latest stock release.
![debug1](https://user-images.githubusercontent.com/1015121/103455561-185eff00-4ce6-11eb-92e5-4f6e40b947e2.png)

**Comment by drhelius** [comment]
Thanks for reporting!

It's probably due to the protection or the custom mapper in the game that is tricking the emulator. I'm not going to participate in a commercial rom hacking but if you share the rom I can check if there is a bug in the emulator.

**Comment by drhelius** [comment]
Looking at the image I can see a simple explanation without being a bug in the emulator. In a first pass, the emulator goes through 037D, 0380, 0381 normally and without issues, later and incorrectly the game jumps to 037F, then the emulator interpret it as a JP to RAM.

**Comment by WaferMouse** [comment]
I've just confirmed that using Emulicious and you're absolutely on the money. My apologies, no bug here, at least not with your code :)
