### ISSUE TITLE
"Pro Action Replay" codes not accepted

### ISSUE THREAD

**Issue by Gliese64** [drhelius/Gearsystem#35]
If I try to enter a 9 character long "Pro Action Replay" cheat code (e.g. "00D1-4007"), the function main_menu() in platforms/desktop-shared/gui.cpp, don't add it because there's a check in line 386 if the input 7, 8 or 11 characters long:

<code>if ((cheat_list.size() < 10) && ((cheat.length() == 7) || (cheat.length() == 8) || (cheat.length() == 11)))</code>

The function SetProActionReplayCheat() in src/processor.cpp wants a 9 character long input:
<code>
void Processor::SetProActionReplayCheat(const char* szCheat)
...<br>
    if (code.length() == 9)<br>
...<br>
</code>

**Comment by drhelius** [comment]
Thanks for reporting!

I'm looking into it.

**Comment by drhelius** [comment]
Fixed in 07b447cdc416b2a9cc5eaac7975fbe9a639120e9

Now it accepts `1234-5678` and `12345678` formats.

Thanks!
