### ISSUE TITLE
Retroarch Quick Menu > Restart

### ISSUE THREAD

**Issue by kenseiden** [drhelius/Gearsystem#41]
When running any Master System rom on Gearsystem and choosing to restart from retroarch quick menu, it causes to crash and close the game.

**Comment by drhelius** [comment]
Thanks for reporting, I can't reproduce it.

Which platform and version of Gearsystem core are you using?

**Comment by kenseiden** [comment]
I’m playing on Anbernic RG351P using 351ELEC firmware, the platform is Master System and the core version is 3.2.0.

A friend is playing on an updated firmware but same core version 3.2.0 and is having the same problem when trying to restart from Retroarch.

**Comment by drhelius** [comment]
Yep, it's failing in 3.2.0 but it's fixed in 3.3.0.
Gearsystem master branch is currently at 3.3.0.
If you could test the latest version we can verify it's fixed and close the issue.

**Comment by kenseiden** [comment]
For some reason the “Update Cores” feature is missing in my retroarch but I believe you so I’ll close the issue, thanks!
