### ISSUE TITLE
Light Phaser support

### ISSUE THREAD

**Issue by projetto** [drhelius/Gearsystem#43]
I'm using it and it's very good. To replace completely my old sms emu it lacks some feature.

Light phaser support maybe also paddles
3d glasses support (choose to display only left or right eye)
Graphic filters (super eagle, Hq, ecc.)
Bios boot support

**Comment by drhelius** [comment]
Thanks for your suggestions!

**Comment by drhelius** [comment]
BIOS support added!!

3D glasses and light phaser may come next.

**Comment by drhelius** [comment]
Changed name of issue as Light Phaser is the only feature left to add.

Graphics filters have its own issue too (#47).

**Comment by drhelius** [comment]
* Gangster Town (UE) [!]
* Marksman Shooting - Trap Shooting (U) [!]
* Operation Wolf (EB) [!]
* Rambo III (UE) [!]
* Rescue Mission (UE) [!]
* Shooting Gallery (UE) [!]

From #67
