### ISSUE TITLE
Janggun Mapper

### ISSUE THREAD

**Issue by carmiker** [drhelius/Gearsystem#46]
Currently, Gearsystem does not properly support the Janggun mapper, used by `Janggun-ui Adeul`.

As luck would have it, I documented the mapper at smspower a few months ago:
https://www.smspower.org/Development/Mappers#JanggunMapper

You can also see my implementation of it in C here:
https://gitlab.com/jgemu/cega/-/blob/master/core/cega_sms.c#L286

**Comment by drhelius** [comment]
That's awesome, thanks for pointing out, I will definitely implement it.
