### ISSUE TITLE
CRT switchres not switching to native resolutions 

### ISSUE THREAD

**Issue by TeddyBeer1983** [drhelius/Gearsystem#49]
Does this core work with CRT Switchres? All the games boot in 640x480

**Comment by drhelius** [comment]
Thanks for your question. 
I'm not familiar with it. I don't even know if I need to do something on the core or if this is something managed by RA, but I'll take a look.

**Comment by TeddyBeer1983** [comment]
Thank you very much

**Comment by drhelius** [comment]
AFAIK this is an issue with RA as there is nothing I can do in the core except reporting the right resolution for each console and region, and this is already being done.

Is this core the only one failing to you? Could you share any more details about your setup?

**Comment by TeddyBeer1983** [comment]
Here's how it's going:

I have a PC connected to a CRT with each console's native resolution except Atari 2600 and Master System...BUT... SMS native resolutions work when I use Genesis Plus GX AND with the top/bottom borders.

**Comment by drhelius** [comment]
Sorry for the delay.

I just implemented correct overscan sizing and options to enable/disable it within the core. 

It would be possible now to enable top+bottom borders and the right sizing should be reported by the core. Probably this issue is solved.
