### ISSUE TITLE
Output image is not pixel perfect

### ISSUE THREAD

**Issue by Jaffacakelover** [drhelius/Gearsystem#57]
Gearsystem 3.4.1, Windows 10 Home x64. Filtering off, ghosting off, scanlines off. Square pixels ratio (although nothing changes when 4:3 is set).

Zooming in on the title screen of Bank Panic, you can see that the scaling / display is not pixel perfect, aliasing edges of both the game image and the edges of the game window:
![Bank Panic x3 x4 1](https://user-images.githubusercontent.com/3490850/147602546-c7c3e250-cfcc-4659-b3bc-97dd93372632.png)
`3x scale, 400% zoom`

It doesn't scale cleanly up from / down to 256x192. Even 1x (actual size) isn't a crisp picture:
![Bank Panic x1 x4 1](https://user-images.githubusercontent.com/3490850/147602558-5e41de43-bf0d-42b4-abdb-c1a352d6411e.png)
`1x scale, 400% zoom`

How it should look when zoomed in:
![Bank Panic 1x 4x clean](https://user-images.githubusercontent.com/3490850/147602578-581fc799-42eb-40d0-b558-27e05c083638.png)
`1x scale, 400% zoom, from another emulator`

**Comment by drhelius** [comment]
Thanks for reporting, I'll take a look

**Comment by drhelius** [comment]
I can't reproduce the issue. I tested on Windows and Linux and got pixel prefect images.
What resolution are you using?

**Comment by drhelius** [comment]
I was able to reproduce it by setting the Windows scale (Settings > System > Display) to a value higher than 100%
Is that your case?

**Comment by Jaffacakelover** [comment]
Yes, that's it! My laptop was set to 125% scale, and setting it to 100% solved the problem.

Looking at the emulator I was comparing Gearsystem to, it looks like they've implemented it so that the menu bar etc. scales with that DPI setting, but the game window stays the same size regardless!

![biz-100](https://user-images.githubusercontent.com/3490850/147687295-e49d39e4-6b9d-41cd-bf18-0c6b1a1976b4.PNG)
`Scale 100%`

![biz-125](https://user-images.githubusercontent.com/3490850/147687303-5594db58-816c-47b6-8641-3d450e7f8b4b.PNG)
`Scale 125%`

**Comment by drhelius** [comment]
OK! I'll fix it so it renders correctly even at 125%
