### ISSUE TITLE
Feature Request: Fit Window to Output

### ISSUE THREAD

**Issue by jet082** [drhelius/Gearsystem#58]
It is a bit frustrating to have the image of the game with so much dead space around it. It would be nice if the window itself could be resized to fit 100% of the output content. That way, we could have integer scaling, but no dead space.

![image](https://user-images.githubusercontent.com/46708077/152353041-a7c93141-bc42-405f-b3ff-ab77588d6b89.png)

**Comment by drhelius** [comment]
I understand integer scale as a pixel perfect scaling factor, x2, x3, x4, etc. applied to the width and height of the original image.

When setting "Scale" to "Auto" the emulator is finding the higher factor possible for the current window size. If you resize the window it will recalculate it as required.

If I understand correctly, what you are asking is not integer scaling, it is fit to height, right? AKA using all the height of the window and at the same time keeping the aspect ratio. That will produce a non integer scaling factor but could be added anyway.

**Comment by drhelius** [comment]
After rereading the issue again I understand the problem. I'll fix it soon.
