### ISSUE TITLE
Can You Please Create A Gearsystem Emulator For Android

### ISSUE THREAD

**Issue by SopTheSop2022** [drhelius/Gearsystem#59]
Please Create Gearsystem Emulator For Android. It Will Be Also Free

**Comment by drhelius** [comment]
Sorry, thanks for your query but not interested. Anyway, the beautiful of OSS is that all the code is available and anyone can!

Also, you can use the Gearsystem core for Retro Arch in Android: https://docs.libretro.com/library/gearsystem/
