### ISSUE TITLE
Add Support For SC-3000, SF-7000

### ISSUE THREAD

**Issue by ghost** [drhelius/Gearsystem#60]
Can You Please Add Support For SC-3000, SF-7000, Sega Genesis/Megadrive, Sega CD, Sega 32X. Also Add Master System YM2413 FM Sound Unit On/Off.

**Comment by SopTheSop2022** [comment]
Oops. You Can Add Master System YM2413 FM Sound Unit On/Off. Master System YM2413 Is Used On Out Run, Penguin Land, Wonder Boy In Monster Land, Game De Check! koutsuu anzen

**Comment by DVDVIDE** [comment]
@drhelius YM2413 Is A Master System Sound Chip. Used On Penguin Land Game, Wonder Boy In Monster Land & Other

**Comment by drhelius** [comment]
Changed title to keep the feature request for SC-3000 and SF-7000.

YM2413 have its own issue: #61

**Comment by MinecraftMario27** [comment]
YM2413 is an FM sound chip. Mark III and Japanese Master System has YM2413 FM

**Comment by drhelius** [comment]
Closing as I'm not doing implementing SC-3000, SF-7000 any time soon.
YM2413 has its own issue: https://github.com/drhelius/Gearsystem/issues/61
