### ISSUE TITLE
Hide Mouse Cursor in Fullscreen

### ISSUE THREAD

**Issue by xenrique-cc** [drhelius/Gearsystem#62]
I believe there is no current feature for it, it would be nice if there were an option to enable hiding the mouse cursor while in fullscreen.

**Comment by drhelius** [comment]
Thanks, I'll add it soon

**Comment by drhelius** [comment]
I end up hiding the cursor when main menu is disabled that I think it makes more sense.
It also hides when you hover over the main output window.
