### ISSUE TITLE
188-in-1 SMS mapper support

### ISSUE THREAD

**Issue by litaniast** [drhelius/Gearsystem#63]
https://www.smspower.org/

According to SMS Power!, they dumped new Korean SMS multicart 188-in-1, only the conversion of MSX games.
It has the mapper that previously unknown, so it needs to support it in emulator.

**Comment by drhelius** [comment]
Thanks for reporting

**Comment by litaniast** [comment]
More SMS multicarts from Korea were dumped. Needs support those mappers too. https://www.smspower.org/forums/19521-26thAnniversaryKoreanSMSMulticartsGalore1OngoingCompetitions
