### ISSUE TITLE
Sega Genesis/Mega Drive, Sega CD, Sega 32X, Sega 32X CD Support

### ISSUE THREAD

**Issue by SteveCraft27** [drhelius/Gearsystem#65]
Sega Genesis / Mega Drive: .md, .bin, .smd, File Extension

Sega Mega CD / 32X CD: .cue, .chd File Extension

Sega 32X: .32x File Extension 

Sega Genesis / Mega Drive, Sega Mega CD / 32X CD, Sega 32X Uses D-Pad, Mode Button, Start Button, A, B, C, X, Y, Z Button.

Master System, Game Gear, SG-1000 Uses D-Pad Start Button, B, C Button.

**Comment by drhelius** [comment]
Sorry there are no plans to add Genesis support (and the like) to this emu right now
