### ISSUE TITLE
Add Crop Overscan / Borders options

### ISSUE THREAD

**Issue by ghost** [drhelius/Gearsystem#68]
For Sega SG-1000 / ColecoVision / Microsoft MSX1 / SVI SpectraVideo / Sega SC-3000 / Sega SF-7000 / Sega Master System:

256x192 SG-1000 / Master System
![256x192](https://user-images.githubusercontent.com/107685666/179748122-06b7f0f7-e039-45dc-bfb6-c98339428ada.png)
256x240 SG-1000 / Master System
![256x240](https://user-images.githubusercontent.com/107685666/179748252-7cfe1126-7de0-4a75-98d0-38b45a80abc4.png)
320x240 SG-1000 / Master System
![320x240](https://user-images.githubusercontent.com/107685666/179748346-b1d174e7-4da8-4470-8d0e-db84ae8c7894.png)

For Sega Genesis / Mega Drive / CD / 32X:

320x224 Genesis / Mega Drive / CD / 32X
![320x224 Genesis](https://user-images.githubusercontent.com/107685666/179748485-33e4354b-29c6-4cd8-815b-cdb42ba6fbf6.png)
320x240 Genesis / Mega Drive / CD / 32X
![320x240 Genesis](https://user-images.githubusercontent.com/107685666/179748514-cd2f868f-e945-4539-929e-f640d912f969.png)

**Comment by drhelius** [comment]
Thanks for reporting! It's already described in #64
