### ISSUE TITLE
Not support for OpenGL 3.0 ?

### ISSUE THREAD

**Issue by Augusto7743** [drhelius/Gearsystem#72]
Hello.
What is required OpenGL version ?
Trying use with OpenGL 3.0 not start the emulator libretro core.

Thanks for reply.

**Comment by Augusto7743** [comment]
Not any reply ?
I had reported not is possible start that core if using OpenGL 3.0

**Comment by drhelius** [comment]
Sorry, this is not an OpenGL enabled core. I don't know what are you talking about. Maybe an error with Retro Arch?

**Comment by Augusto7743** [comment]
Exactly was an Retroarch bug in previous versions.
Retroarch current version works correctly if using Vulkan.
Thanks for reply and for making gearsystem.
Have an nice day.
