### ISSUE TITLE
[Libretro] Add 4:3 aspect ratio to Game Gear

### ISSUE THREAD

**Issue by dfreivald** [drhelius/Gearsystem#73]
I think this could be 4:3 given the non-square pixels of the GG LCD.

**Comment by drhelius** [comment]
You're right, I'll take a look, maybe with an option to choose the one you prefer.

**Comment by dfreivald** [comment]
Certainly not urgent - RA allows you to set the aspect ratio as an override. The core as is looks and and runs great in 4:3.
