### ISSUE TITLE
Feature Request: Load Symbol Maps From Command Line

### ISSUE THREAD

**Issue by Pokeman2003** [drhelius/Gearsystem#75]
Pretty much on the tin. We can already load ROMs from the command line, so why not symbol maps? It would make automating my debugging way easier.

Also, it would probably behoove you to implement a CLI help prompt, under something like a /? or --? flag.

**Comment by drhelius** [comment]
Yep, nice to have.

If you are using the emulator as a debugger any feedback you have will be greatly appreciated. Don't hesitate to open more feature request if you miss something or can be improved.

Thanks for your help.

**Comment by Pokeman2003** [comment]
I'm currently setting everything up to do so. I'll let you know when I encounter things that I think could use feedback.

While I'm here, what's with the custom UI instead of Win32? Is that just the result of a cross-platform library you're using? I don't mind it, but it does ever so slightly bug me because it doesn't look consistent with the rest of my programs :P

**Comment by drhelius** [comment]
The UI is https://github.com/ocornut/imgui
It is extremely easy to use and let me focus on the emulation part, and it is also portable.
I used Qt in the past and it was a pita.

**Comment by Pokeman2003** [comment]
So I've heard from one of my other developer friends. They liked early Qt.

**Comment by drhelius** [comment]
The emulator tries to load automatically a symbol file at the same time a rom is being loaded.
For example, for ```path_to_rom_file.sms``` it tries to load ```path_to_rom_file.sym```

This was already implemented. I just added an option to load a symbol file using the command line too:
```Usage: gearsystem [rom_file] [symbol_file]```
