### ISSUE TITLE
Implement WLA Symbol file format

### ISSUE THREAD

**Issue by Pokeman2003** [drhelius/Gearsystem#76]
So I utilize WLA-DX for compilation. It creates a symbol map that looks like this.
[230507-11190651.txt](https://github.com/drhelius/Gearsystem/files/11415724/230507-11190651.txt)
Now, I'm not positive, but I suspect this is just the result of you not having a WLA Symbol parser, and whatever parser you do have is just interpreting the file to the best of its abilities. If this is the case, then it explains why the definitions section(used for variable names) is being output as if they are labels and NOT as variables.
![image](https://user-images.githubusercontent.com/83632748/236696100-18dc3223-fa56-4bb0-b37a-93774fedcf76.png)
If I'm correct about the lack of a WLA parser, and you plan on implementing a symbol map parser for WLA, here's a link to [version 1](https://github.com/vhelin/wla-dx/blob/v9.12/doc/symbols.rst) and [version 2](https://github.com/vhelin/wla-dx/blob/master/doc/symbols.rst) of their standard.

**Comment by drhelius** [comment]
Thanks, that's right, this format is not supported and the parser is doing its best right now.
The "labels" section of the file is probably working right though.
