### ISSUE TITLE
Scrolling Not Handled Appropriately On Disassembler

### ISSUE THREAD

**Issue by Pokeman2003** [drhelius/Gearsystem#77]
I don't have images for this one, but it's pretty simple to replicate on 3.4. Get any ROM, and try to scroll in the disassembler while paused. At best, if you hold the scroll bar, you'll be able to look, but the moment you let go of the scroll bar, it'll reset its position back to where the last command executed. However, using the scroll wheel is utterly pointless because it will scroll up/down for exactly one frame, and then reset its position.

**Comment by drhelius** [comment]
That's because you have "Follow PC" enabled. Disable it and you will be able to scroll freely, enable it again to go back to the program counter.

**Comment by Pokeman2003** [comment]
Oh. That's rather counter intuitive, in my opinion, but I suppose that's not really a bug then.

**Comment by drhelius** [comment]
I may change it so it disables automatically when you scroll
