### ISSUE TITLE
Possibility Of Running Games By Default In 50fps?

### ISSUE THREAD

**Issue by pferreira1983** [drhelius/Gearsystem#80]
Is there any possibility of having the emulator in RetroArch defaulting PAL exclusive Master System games at the correct 50fps? Games automatically run at 60fps for all SMS PAL games however I have encountered an issue where Outrun 3D which never got a Brazil 60fps release  is running automatically at 60fps instead of 50fps. Changing the region from Auto to PAL in RetroArch threatens to disable Hardcore Mode on Retro Achievements since it considers 50fps cheating. But the Master System version should really be running at 50fps.

It would also be great to have this option of switching for PAL games that had a Brazilian 60fps release like Sonic Chaos or any other PAL SMS game.

**Comment by drhelius** [comment]
Sure, it is possible. Could you help me with the list of those kind of games or point me to any list I can use for that purpose.

The emulator has a small database inside based on CRC to decide witch rom is pal or the fps for is not taking into account this cases.

**Comment by hb-robo** [comment]
The only list I know of that supports region filtering for Master System games [is on Wikipedia](https://en.wikipedia.org/wiki/List_of_Master_System_games), if you click the headers in the order PAL->BR->NA->JP the top of the list will populate with (presumed) PAL-only titles. Using that method, I'm seeing 159 titles starting from "Bank Panic" all the way through "The Smurfs 2: Travel the World", however they will likely have to be individually verified as I can see a couple, such as the aforementioned Sonic Chaos, that did have BR releases that are not logged in the table.

**Comment by pferreira1983** [comment]
I had no idea there was even 159 titles that were just PAL. The ability to play at 50fps by default would be great for these titles along with titles that did get a Brazilian release like Sonic Chaos, Castle of Illusion, Lucky Dime Caper, etc as the argument can be made that they are supposed to be running in 50fps. LDC in particular sounds too fast in 60fps.

**Comment by pferreira1983** [comment]
> Sure, it is possible. Could you help me with the list of those kind of games or point me to any list I can use for that purpose.
> 
> The emulator has a small database inside based on CRC to decide witch rom is pal or the fps for is not taking into account this cases.

I had no idea there was even 159 titles that were just PAL. The ability to play at 50fps by default would be great for these titles along with titles that did get a Brazilian release like Sonic Chaos, Castle of Illusion, Lucky Dime Caper, etc as the argument can be made that they are supposed to be running in 50fps. LDC in particular sounds too fast in 60fps.

**Comment by pferreira1983** [comment]
> The only list I know of that supports region filtering for Master System games [is on Wikipedia](https://en.wikipedia.org/wiki/List_of_Master_System_games), if you click the headers in the order PAL->BR->NA->JP the top of the list will populate with (presumed) PAL-only titles. Using that method, I'm seeing 159 titles starting from "Bank Panic" all the way through "The Smurfs 2: Travel the World", however they will likely have to be individually verified as I can see a couple, such as the aforementioned Sonic Chaos, that did have BR releases that are not logged in the table.

Don't trust Wiki. I have found out Outrun 3D was released in Brazil. Again it should probably be played in 50fps but it was released in that country. I've tried numerous examples of PAL Euro only releases and they run at 50fps however the option to play the PAL games that were released in Brazil at 50fps would be an option I would like to see.

**Comment by hb-robo** [comment]
Unfortunately sounds like the games need to be checked individually. The IGDB API also accepts querying parameters so it may be possible to search for MS games released in PAL but not BR using that.

**Comment by pferreira1983** [comment]
> Unfortunately sounds like the games need to be checked individually. The IGDB API also accepts querying parameters so it may be possible to search for MS games released in PAL but not BR using that.

Probably...or just use SMS Power like I did to check. 😁

**Comment by drhelius** [comment]
I wasn't aware of so many pal only games. I will probably start with that list of 159 titles and improve on that. The task is simple because as I said the emulator already has the ability to keep an internal databases but is tedious to add one by one so it may take some time.

Thanks for all the help

**Comment by pferreira1983** [comment]
> I wasn't aware of so many pal only games. I will probably start with that list of 159 titles and improve on that. The task is simple because as I said the emulator already has the ability to keep an internal databases but is tedious to add one by one so it may take some time.
> 
> Thanks for all the help

Sega stopped supporting Master System in North America by 1991. There was a huge amount of games still released after that for Europe and Brazil. I would certainly use the SMS Power website as reference for research. Will be great if you manage to tag the games somehow. The emulator through RetroArch is determined to play all the PAL games in 60fps if the option is available even if it wasn't originally intended as the correct speed of a game.

**Comment by drhelius** [comment]
Games that only work correctly on PAL (50Hz) systems:
https://www.smspower.org/Tags/PALOnly

**Comment by pferreira1983** [comment]
> Games that only work correctly on PAL (50Hz) systems: https://www.smspower.org/Tags/PALOnly

This is great work. I will say however certain PAL games that have a 60fps option for Brazil like Lucky Dime Caper should be running in 50fps. The music is a dead giveaway.

**Comment by drhelius** [comment]
I just included the whole list. Please take a look at here and feel free to point me to any corrections or new additions:

https://github.com/drhelius/Gearsystem/blob/531a0f65a69c9867ebefbc4c39edc45f828bd304/src/game_db.h#L64
