### ISSUE TITLE
More SMS multicart dumped.

### ISSUE THREAD

**Issue by litaniast** [drhelius/Gearsystem#81]
I used to playing them in other core(lr-genesis-plus-gx) but unfortunately currently its author seems to a bit busy.
So we can't play them on any libretro cores.

https://www.smspower.org/forums/19754-KoreanSMSMulticartsGalore2
https://www.smspower.org/forums/19789-KoreanSMSMulticartsGalore3

Needs support their mappers to play them. Please

**Comment by litaniast** [comment]
Like them https://github.com/drhelius/Gearsystem/issues/63

**Comment by drhelius** [comment]
Added most if not all known multi-cart mappers out there
