### ISSUE TITLE
Game Gear - Colors off on Virtua Fighter Animation/Mini

### ISSUE THREAD

**Issue by unit3uk** [drhelius/Gearsystem#83]
The colors are off on Virtua Fighter Animation and Virtua Fighter Mini when the match starts. It happens on the Libretro core and standalone.
![Virtua Fighter Mini](https://github.com/drhelius/Gearsystem/assets/95283208/b295c15d-cc0a-455c-9998-53a24adff7d9)

**Comment by drhelius** [comment]
Thanks for reporting
