### ISSUE TITLE
TMS9918 on Master System / Mark III mode

### ISSUE THREAD

**Issue by MinecraftMario27** [drhelius/Gearsystem#87]
TMS9918 on Master System / Mark III hardware actually uses dark color palette
![Wonder Boy (J) (SG-1000) (V1 1)-240111-204721](https://github.com/drhelius/Gearsystem/assets/137607853/35a44895-d438-4fbb-be1b-92fe25a557c2)
That's how TMS9918 look on real Master System / Mark III hardware

**Comment by drhelius** [comment]
I have not fully understood your request.

I'm emulating a SG-1000 and it uses the "soft" palette (https://www.smspower.org/Development/Palette#SG1000SC3000).

Are you saying that if you force "Master System / Mark II/" via emulator options it should use the dark palette? That something I could do, but user has to explicitly select "Master System / Mark III" hardware and not "Auto".

**Comment by drhelius** [comment]
Let me know if this is what you were looking for.

**Comment by kusfo** [comment]
I'm not the OP, but I can see how this can be useful. Imagine you're developing a SG-1000 homebrew, you may want to test how it'll look both in an original SG-1000 and on a Mark-III/Master System.

**Comment by drhelius** [comment]
Yes, that's what I basically implemented in the mentioned commit.
