### ISSUE TITLE
Broken libretro builds for Android

### ISSUE THREAD

**Issue by LibretroAdmin** [drhelius/Gearsystem#89]
Hi,

the libretro builds for Android have been broken for a few days now.

See this for reference -
https://git.libretro.com/libretro/gearsystem/-/pipelines/243705

**Comment by drhelius** [comment]
Thanks, I see the problem.

Is there anyway I can get notified directly from gitlab so you don't have to spend time opening this issues?

**Comment by drhelius** [comment]
Fixed in 43afdaf
