### ISSUE TITLE
[Issue] Audio isn't working

### ISSUE THREAD

**Issue by SopTheSop25** [drhelius/Gearsystem#91]
On Latest version build, I hear no audio sound

**Comment by drhelius** [comment]
What platform are you testing? 

If you are using the desktop version can you share the build version that shows in the "About" window? 

Didn't change anything related to audio, could you recheck your settings?

**Comment by SopTheSop25** [comment]
I used RetroArch, audio isn't working on Gearsystem core, but it works on other emulators

**Comment by SopTheSop25** [comment]
https://github.com/drhelius/Gearsystem/assets/123488084/268b9093-d988-4544-95bd-48a0035e1afe

**Comment by SopTheSop25** [comment]
https://github.com/drhelius/Gearsystem/assets/123488084/2b9c020a-2d9b-4637-a739-06003c6757ea

**Comment by drhelius** [comment]
You are completely right. Thanks for reporting!

**Comment by drhelius** [comment]
Solved in 247fba5
